# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: |
      ./autogen.sh --prefix=/tmp/test-install --disable-nls --disable-btls --disable-boehm
    displayName: 'Autogen + Configure'

  - script: |
      make
    displayName: 'Build Mono'

  - script: |
      make install
    displayName: 'Install new version of Mono into /tmp'

-job: macOS
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: |
      ./autogen.sh --prefix=/tmp/test-install --disable-nls --disable-btls --disable-boehm
    displayName: 'Autogen + Configure'

  - script: |
      make
    displayName: 'Build Mono'

  - script: |
      make install
    displayName: 'Install new version of Mono into /tmp'

